name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Unit tests
        run: go test ./pkg/... -v

      - name: Lint
        run: go vet ./...

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Build
        run: go build -o /usr/local/bin/minic ./cmd/minic

      - name: Pull Alpine rootfs
        run: sudo bash scripts/download-rootfs.sh

      - name: E2E tests
        run: sudo go test ./tests/... -v -tags e2e -timeout 120s
